name: Docker

on: 
  push:
    branches:
      - test
jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:20-alpine
      #credentials:
      #  username:
      #  password:
      env:
        API_URL: url.com
      ports:
        - 80
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env 
        run: echo $API_URL
